#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses

sudo cp /etc/hosts /tmp/hosts
sudo sed 's/127.0.0.1/127.0.0.2/' /tmp/hosts > /tmp/hosts.new
echo "8.8.8.8 facebook.com" | sudo tee -a /tmp/hosts.new > /dev/null
sudo cp /tmp/hosts.new /etc/hosts
